
  - platform: ring

  # Motion sensors ##################################3
  ## Motion sensors #########
  - platform: mqtt
    state_topic: "caja_tv/motion"
    name: motion_tvroom
    payload_on: "1"
    payload_off: "0"
    device_class: motion
    off_delay: 60

  - platform: mqtt
    state_topic: "xbeebox/jardin/motion/1/caja_terraza"
    name: motion_terraza
    payload_on: True
    payload_off: False
    device_class: motion
    off_delay: 60

  - platform: mqtt
    name: motion_sala
    state_topic: "xbeebox/sala/motion/1/cajasala"
    payload_on: True
    payload_off: False
    device_class: motion
    off_delay: 30
  - platform: mqtt
    state_topic: "xbeebox/estudiof/motion/1/caja_estudiof"
    name: motion_estudiof
    payload_on: True
    payload_off: False
    device_class: motion
  - platform: mqtt
    state_topic: "xbeebox/estudiot/motion/1/caja_estudiot"
    name: motion_estudiot
    payload_on: True
    payload_off: False
    device_class: motion
    off_delay: 60
  - platform: mqtt
    state_topic: "xbeebox/recamara_principal/motion/1/cajarecamara"
    name: motion_recamara
    payload_on: True
    payload_off: False
    device_class: motion
    off_delay: 60
  - platform: mqtt
    name: motion_pasillo_recamaras
    state_topic: "xbeebox/pasillo_recamaras/samples/caja_pasillo_recamaras"
    payload_off: False
    payload_on: True
    device_class: motion
    value_template: '{{ value_json[0]["dio-4"] }}'
    off_delay: 10

  - platform: mqtt
    name: motion_bano_visitas
    state_topic: "xbeebox/bano_visitas/samples/caja_bano_visitas"
    payload_off: False
    payload_on: True
    value_template: '{{ value_json[0]["dio-1"] }}'
    device_class: motion
    off_delay: 60

  - platform: mqtt
    name: motion_hall_entrada
    state_topic: "xbeebox/hall_entrada/samples/caja_puerta"
    payload_off: False
    payload_on: True
    value_template: '{{ value_json[0]["dio-1"] }}'
    device_class: motion
    off_delay: 10

  - platform: mqtt
    name: motion_bano_principal
    state_topic: "xbeebox/bano_principal/samples/caja_bano_principal"
    payload_off: False
    payload_on: True
    value_template: '{{ value_json[0]["dio-1"] }}'
    device_class: motion
    off_delay: 10

  - platform: mqtt
    name: motion_pasillo_comedor_1
    state_topic: "xbeebox/pasillo_comedor/motion/1/caja_pasillo_comedor"
    payload_on: True
    payload_off: False
    device_class: motion
    off_delay: 10
  - platform: mqtt
    name: motion_pasillo_comedor_2
    state_topic: "xbeebox/pasillo_comedor/motion/2/caja_pasillo_comedor"
    payload_on: True
    payload_off: False
    device_class: motion
    off_delay: 10
  - platform: mqtt
    name: motion_comedor
    state_topic: "xbeebox/comedor/motion/1/caja_comedor"
    payload_on: True
    payload_off: False
    device_class: motion
    off_delay: 60

  - platform: mqtt
    name: motion_cocina
    state_topic: "xbeebox/cocina/motion/1/cajacocina"
    payload_on: True
    payload_off: False
    device_class: motion
    off_delay: 30

## Camera motion
  - platform: mqtt
    name: motion_camera_hall
    state_topic: "zoneminder/1"
    value_template: '{{ "ON" }}'
    device_class: motion
    off_delay: 8
  - platform: mqtt
    name: motion_camera_puerta_patio
    state_topic: "zoneminder/3"
    value_template: '{{ "ON" }}'
    device_class: motion
    off_delay: 8
  - platform: mqtt
    name: motion_camera_patio
    state_topic: "zoneminder/5"
    value_template: '{{ "ON" }}'
    device_class: motion
    off_delay: 8
  - platform: mqtt
    name: motion_camera_escaleras
    state_topic: "zoneminder/6"
    value_template: '{{ "ON" }}'
    device_class: motion
    off_delay: 8




######### door sensors ########

## Doors and windows
  - platform: mqtt
    name: Felipe window
    state_topic: door_window/felipe_study
    payload_on: "open"
    payload_off: "closed"
    device_class: window
  - platform: mqtt
    name: Kitchen door
    state_topic: door_window/kitchen_door
    payload_on: "open"
    payload_off: "closed"
    device_class: door
  - platform: mqtt
    name: Tita door
    state_topic: door_window/tita_door
    payload_on: "open"
    payload_off: "closed"
    device_class: door
  - platform: mqtt
    name: Main Garden door
    state_topic: door_window/main_garden_door
    payload_on: "open"
    payload_off: "closed"
    device_class: door
  - platform: mqtt
    name: Main Bathroom
    state_topic: door_window/main_bath
    payload_on: "open"
    payload_off: "closed"
    device_class: door
  - platform: mqtt
    name: Workshop
    state_topic: door_window/workshop_door
    payload_on: "open"
    payload_off: "closed"
    device_class: door
  - platform: mqtt
    name: Hall
    state_topic: "xbeebox/hall_entrada/samples/caja_puerta"
    payload_off: True
    payload_on: False
    value_template: '{{ value_json[0]["dio-2"] }}'
    device_class: door
  - platform: mqtt
    name: Patio gate
    state_topic: "sonoff/patio_door/cmnd/POWER2"
    payload_on: "ON"
    payload_off: "OFF"
    device_class: door




##############################

## Timbre en patio
  - platform: mqtt
    name: "patio doorbell"
    state_topic: xbeebox/patio/timbre/1/caja_garage
    payload_on: "1"
    payload_off: "0"


######### high water usage ###########
  - platform: trend
    sensors:
      high_water_usage:
        entity_id: sensor.water_tank_liters
        device_class: moisture
        friendly_name: High water usage
        max_samples: 1000
        sample_duration: 120
        min_gradient: -0.1
