
frontend:
config: 
history:
logbook:
map:
mobile_app:
ssdp:
sun:
system_health:
updater:


homeassistant:
  name: Cuauhtemoc97
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: America/Mexico_City
  customize: !include customize.yaml
  packages: !include_dir_named packages

logger:
  default: info

person:

lovelace:
  mode: yaml

recorder:
  db_url: !secret hass_db
  purge_keep_days: 30
  exclude: 
    entities:
      - weather.dark_sky 
      - sun.sun
      - sensor.date_time
      - sensor.time
      - sensor.time_date
      - sensor.date
      - sensor.iphonesef_battery_level
      - sensor.iphonesef_battery_state
      - sensor.iphone_tere_battery_level
      - sensor.iphone_tere_battery_state
      - camera.front_door
      - sensor.memory_free
      - sensor.load_1m
      - sensor.ups_time_left
      - sensor.ups_loadpct
      - image_processing.opencv_hall
      - sensor.water_tank_distance_raw
      - sensor.water_tank_distance_filtered
      - binary_sensor.high_water_usage
      - sensor.water_usage_rate
      - sensor.ups_load
      - sensor.washing_machine_stats_mean
      - sensor.cuauhtemoc_dew_point_2
      - sensor.cuauhtemoc_dew_point
      - binary_sensor.pressure_falling
      - sensor.bedroom_photo_level
      - sensor.pressure
      - sensor.xeoma_host_containers_active
      - sensor.xeoma_host_containers_cpu_used
      - sensor.xeoma_host_containers_ram_used
      - sensor.xeoma_host_cpu_load
      - sensor.xeoma_host_cpu_temp
      - sensor.xeoma_host_cpu_used
      - sensor.xeoma_host_disk_free
      - sensor.xeoma_host_disk_used
      - sensor.xeoma_host_disk_used_percent
      - sensor.xeoma_host_ram_free
      - sensor.xeoma_host_ram_used
      - sensor.xeoma_host_ram_used_percent
      - sensor.xeoma_host_running
      - sensor.xeoma_host_sleeping
      - sensor.xeoma_host_swap_free
      - sensor.xeoma_host_swap_used
      - sensor.xeoma_host_swap_used_percent
      - sensor.xeoma_host_thread
      - sensor.xeoma_host_total
#script: !include scripts.yaml
#binary_sensor: !include binary_sensor.yaml
#switch: !include switch.yaml
#camera: !include camera.yaml
#media_player: !include media_player.yaml
#automation: !include_dir_merge_list automation/
light: !include lights.yaml
sensor: !include sensors.yaml
#group: !include groups.yaml

mqtt:
  broker: 192.168.100.50
  port: 1883
  client_id: home-assistant-1

ios:

python_script:

notify:
  - name: iphone_tyf
    platform: group
    services:
      - service: mobile_app_iphone_tere
      - service: mobile_app_moto_g_7_power
      - service: mobile_app_fgiphone8

  - name: slackbot
    platform: slack
    api_key: !secret slackbot_key
    default_channel: '#home'
    username: cuau97hass

switch:
  - platform: broadlink
    host: 192.168.100.59
    mac: 'C8:F7:42:21:A7:46'
  - platform: broadlink
    host: 192.168.100.13
    mac: 'C8:F7:42:21:B2:F8'

smartir:

ecovacs:
  username: !secret ecovacs_user
  password: !secret ecovacs_pass
  country: mx
  continent: eu

input_boolean:
  sleep_mode:
    name: "Sleep mode"
    initial: off
    icon: mdi:sleep

cloud:
  alexa:
    entity_config:
      light.bedroom_lights:
        name: "Luces de la recamara"
        description: Luces de recamara principal
        display_categories: LIGHT
      light.dressing_room:
        name: Vestidor
        description: Luces del vestidor
      switch.pool_pump:
        name: Bomba de la alberca
        description: Bomba de la alberca
      sensor.pool_temperature:
        name: alberca
        description: temperatura de la alberca
        display_categories: TEMPERATURE_SENSOR
      light.living_room_lights:
        name: Luces de la sala
        description: Todas las luces de la sala
        display_categories: LIGHT
      light.garden_lights:
        name: "Luces del jardín"
        description: "Todas las luces del jardín" 
        display_categories: LIGHT

automation:
  - alias: notificar reinicio
    trigger:
      platform: homeassistant
      event: start
    action:
    - service: script.sonos_say
      data_template:
        sonos_entity: media_player.living_room
        volume: 0.5
        delay: 00:00:10
        message: El asistente de la casa está iniciado.
automation:
  - trigger:
      platform: template
      value_template: >
        {{ (as_timestamp(strptime(states('sensor.date_time'),'%Y-%m-%d, %H:%M')) - as_timestamp(states.sensor.bedroom_temperature.last_changed) )  > 1800 }}
    action:
      service: notify.iphone_tyf
      data_template:
        message: "La temperatura del cuarto no se ha actualizado."

mqtt_eventstream:
  subscribe_topic: slaves/#
  #   filter:
  #     exclude_entities:
  #       - light.backyard
  #       - light.bedroom_one
  #       - light.bedroom_two
  #       - light.caballeriza_dos
  #       - light.caballeriza_uno
  #       - light.dining_hall_1
  #       - light.dining_hall_2
  #       - light.downstairs_bath
  #       - light.dressing_room
  #       - light.entrance_ahll
  #       - light.entrance_table
  #       - light.front_door
  #       - light.hue_bloom_1
  #       - light.kitchen_lights_day
  #       - light.kitchen_one
  #       - light.kitchen_two
  #       - light.living_room_foot_1
  #       - light.living_room_foot_2
  #       - light.living_room_wall
  #       - light.main_bath_three
  #       - light.main_bath_two
  #       - media_player.office
  #       - light.pasillo_coronas
  #       - light.patio_stairs_one
  #       - light.patio_stairs_two
  #       - light.patio_stairs_three
  #       - light.stairs
  #       - light.study
  #       - light.study_tere
  #       - light.tv_room
