# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:


logger:
  default: info

person:

lovelace:
  mode: yaml

recorder:
  db_url: !secret hass_db
  purge_keep_days: 20
  purge_interval: 1
  exclude: 
    entities:
      - weather.dark_sky 
      - sun.sun
      - sensor.date_time
      - sensor.time
      - sensor.time_date
      - sensor.date
      - sensor.iphonesef_battery_level
      - sensor.iphonesef_battery_state
      - sensor.iphone_tere_battery_level
      - sensor.iphone_tere_battery_state
      - camera.front_door


group: !include groups.yaml
automation: !include_dir_merge_list automation/
script: !include scripts.yaml
binary_sensor: !include binary_sensor.yaml
switch: !include switch.yaml
camera: !include camera.yaml
light: !include lights.yaml
sensor: !include sensors.yaml
media_player: !include media_player.yaml
cover: !include covers.yaml
homeassistant:
  customize: !include customize.yaml

weather:
  - platform: darksky
    api_key: !secret darksky_api_key
###### zoneminder

zoneminder:
  - host: 192.168.100.51
    username: !secret zm_user
    password: !secret zm_pass

# Text to speech
tts:
  - platform: amazon_polly
    aws_access_key_id: !secret aws_access_key_id
    aws_secret_access_key: !secret aws_secret_access_key
    voice: Penelope

mqtt:
  broker: 192.168.100.50
  port: 1883
  client_id: home-assistant-1

ios:

notify:
  - name: iphone_tyf
    platform: group
    services:
      - service: ios_iphone_tere
      - service: ios_iphonesef

ring:
  username: !secret ring_user
  password: !secret ring_pass

apple_tv:
  - name: bedroom_apple_tv
    host: 192.168.100.206
    login_id: !secret apple_tv_login
  - name: tv_room_apple_tv
    host: 192.168.100.15
    login_id: !secret apple_tv_login

shell_command:
  watchdog: 'curl --retry 3 https://hc-ping.com/8ff32001-f721-46be-982f-4b6d2659039b'


##### inputs, timers #############

input_boolean:
  dark_house:
    name: "Dark house"
    initial: off
  auto_light:
    name: "Auto light"
    initial: on
  sleep_mode:
    name: "Sleep mode"
    initial: off
    icon: mdi:sleep
  gate_door_working:
    name: "gate door working"
    initial: off
  gate_state:
    name: "gate state"
    initial: off
  pump_auto:
    name: "Pool pump schedule"
  washing_machine_high:
    name: "washing machine high"
    initial: off
  washing_machine_cycle:
    name: "washing machine cycle"
    initial: off

input_number:
  pool_run_time:
    name: Pool run time
    initial: 3
    min: 1
    max: 6
    step: 1

timer: 
  pump_run:
    duration: '03:00:00'
