
frontend:
config: 
history:
logbook:
map:
mobile_app:
ssdp:
sun:
system_health:
updater:

homeassistant:
  name: Cuauhtemoc97
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: America/Mexico_City
  customize: !include customize.yaml
  packages: !include_dir_named packages

logger:
  default: info

person:

lovelace:
  mode: yaml

recorder:
  db_url: !secret hass_db
  purge_keep_days: 30
  purge_interval: 1
  exclude: 
    entities:
      - weather.dark_sky 
      - sun.sun
      - sensor.date_time
      - sensor.time
      - sensor.time_date
      - sensor.date
      - sensor.iphonesef_battery_level
      - sensor.iphonesef_battery_state
      - sensor.iphone_tere_battery_level
      - sensor.iphone_tere_battery_state
      - camera.front_door
      - sensor.memory_free
      - sensor.load_1m
      - sensor.ups_time_left
      - sensor.ups_loadpct
      - image_processing.opencv_hall
      - sensor.water_tank_distance_raw
      - sensor.water_tank_distance_filtered
      - binary_sensor.high_water_usage
      - sensor.water_usage_rate
      - sensor.zoneminder_host_ram_free
      - sensor.zoneminder_host_cpu_used
      - sensor.ups_load
      - sensor.washing_machine_stats_mean
      - sensor.cuauhtemoc_dew_point_2
      - sensor.cuauhtemoc_dew_point
      - binary_sensor.pressure_falling
      - sensor.bedroom_photo_level
      - sensor.pressure

#script: !include scripts.yaml
#binary_sensor: !include binary_sensor.yaml
#switch: !include switch.yaml
#camera: !include camera.yaml
#media_player: !include media_player.yaml
#automation: !include_dir_merge_list automation/
light: !include lights.yaml
sensor: !include sensors.yaml
group: !include groups.yaml

mqtt:
  broker: 192.168.100.50
  port: 1883
  client_id: home-assistant-1

ios:

python_script:

notify:
  - name: iphone_tyf
    platform: group
    services:
      - service: ios_iphone_tere
      - service: ios_iphonesef

input_boolean:
  sleep_mode:
    name: "Sleep mode"
    initial: off
    icon: mdi:sleep

cloud:
  # alexa:
  #   filter:
  #     exclude_entities:
  #       - light.backyard
  #       - light.bedroom_one
  #       - light.bedroom_two
  #       - light.caballeriza_dos
  #       - light.caballeriza_uno
  #       - light.dining_hall_1
  #       - light.dining_hall_2
  #       - light.downstairs_bath
  #       - light.dressing_room
  #       - light.entrance_ahll
  #       - light.entrance_table
  #       - light.front_door
  #       - light.hue_bloom_1
  #       - light.kitchen_lights_day
  #       - light.kitchen_one
  #       - light.kitchen_two
  #       - light.living_room_foot_1
  #       - light.living_room_foot_2
  #       - light.living_room_wall
  #       - light.main_bath_three
  #       - light.main_bath_two
  #       - media_player.office
  #       - light.pasillo_coronas
  #       - light.patio_stairs_one
  #       - light.patio_stairs_two
  #       - light.patio_stairs_three
  #       - light.stairs
  #       - light.study
  #       - light.study_tere
  #       - light.tv_room
