  - platform: template
    covers:
      street_gate:
        friendly_name: "Gate"
        device_class: garage
        entity_id: input_boolean.gate_state
        value_template: >-
          {% if is_state('input_boolean.gate_state', 'off') %}
            closed
          {% else %}
            open
          {% endif %}
        open_cover:
          service: script.open_gate_timed
        close_cover:
          service: script.close_gate