## Indoors


  - platform: switch
    name: "bano_visitas_techo"
    entity_id: switch.bano_visitas_switch

  - platform: group
    name: "bano_visitas_gp"
    entities:
      - light.bano_visitas_techo
      - light.bano_de_visitas

  - platform: mqtt
    name: "Escritorio de Felipe"
    state_topic: sonoff/lampara_oficina/stat/POWER
    command_topic: sonoff/lampara_oficina/cmnd/POWER
    payload_on: "ON"
    payload_off: "OFF"
    availability_topic: sonoff/lampara_oficina/tele/LWT
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Chicken coop"
    state_topic: sonoff/gallinero/stat/POWER
    command_topic: sonoff/gallinero/cmnd/POWER
    payload_on: "ON"
    payload_off: "OFF"
    availability_topic: sonoff/gallinero/tele/LWT
    payload_available: "Online"
    payload_not_available: "Offline"


  - platform: mqtt
    name: "Patio strip"
    state_topic: "sonoff/basic/serie_patio/stat/POWER"
    command_topic: "sonoff/basic/serie_patio/cmnd/POWER"
    payload_on: "ON"
    payload_off: "OFF"
    availability_topic: "sonoff/basic/serie_patio/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline" 

  - platform: mqtt
    name: "Garden strip"
    command_topic: "xbeebox/caja_terraza/send_tx"
    payload_on: "1"
    payload_off: "0"

  - platform: mqtt
    name: "Kitchen strip"
    command_topic: "xbeebox/cajacocina/send_tx"
    payload_on: "1"
    payload_off: "0"

  - platform: mqtt
    name: "Garden tree lights"
    state_topic: "sonoff/jardin/stat/POWER1"
    command_topic: "sonoff/jardin/cmnd/POWER1"
    payload_on: "ON"
    payload_off: "OFF"
    availability_topic: "sonoff/jardin/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline" 
  - platform: mqtt
    name: "Garden bulbs"
    state_topic: "sonoff/jardin/stat/POWER2"
    command_topic: "sonoff/jardin/cmnd/POWER2"
    payload_on: "ON"
    payload_off: "OFF"
    availability_topic: "sonoff/jardin/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline" 
  - platform: mqtt
    name: "Pool lights"
    state_topic: "sonoff/jardin/stat/POWER3"
    command_topic: "sonoff/jardin/cmnd/POWER3"
    payload_on: "ON"
    payload_off: "OFF"
    availability_topic: "sonoff/jardin/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline" 

  - platform: mqtt
    name: "Laundry light"
    state_topic: sonoff/luzlavado/stat/POWER
    command_topic: sonoff/luzlavado/cmnd/POWER
    payload_on: "ON"
    payload_off: "OFF"
    availability_topic: sonoff/luzlavado/tele/LWT
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: group
    name: Luces del jardin
    entities:
      - light.garden_tree_lights
      - light.garden_bulbs
      - light.pool_lights

  - platform: group
    name: Luces de sala
    entities:
      - light.sala
      - light.reflectores_sala

  - platform: group
    name: Luces del Comedor
    entities:
      - light.comedor
      - light.hue_bloom_1

  - platform: group
    name: Luces de la cocina
    entities:
      - light.cocina
      - light.laundry_light
      - light.kitchen_strip

  - platform: group
    name: Kitchen lights day
    entities:
      - light.kitchen_one
      - light.kitchen_two
      - light.kitchen_strip

  - platform: group
    name: Study Felipe
    entities:
      - light.oficina_de_felipe
      - light.escritorio_de_felipe
      
  - platform: group
    name: Luces del hall de entrada
    entities:
      - light.entrance_hall
      - light.hue_ambiance_pendant_1
      - light.entrance_table

  - platform: group
    name: Luces del bano principal
    entities:
      - light.main_bath_three
      - light.main_bath_two

  - platform: group
    name: Entrada exterior
    entities:
      - light.patio_stairs
      - light.caballeriza
      - light.front_door
      - light.patio_door_lights
      - light.patio_strip

  - platform: group
    name: Terraza de jardin
    entities:
      - light.terrace
      - light.garden_strip

  - platform: group
    name: Luces de recamara
    entities:
      - light.bedroom_one
      - light.bedroom_two

  - platform: group
    name: Pasillo de recamaras
    entities:
      - light.stairs
      #- light.dressing_room

  - platform: group
    name: Luces del Pasillo del comedor
    entities:
      - light.dining_hall_1
      - light.dining_hall_2
