
## Sonos TTS and sound

  sonos_say:
    alias: "Sonos TTS script"
    sequence:
     - service: sonos.snapshot
       data_template:
         entity_id: "{{ sonos_entity }}"
     - service: sonos.unjoin
       data_template:
         entity_id: "{{ sonos_entity }}"
     - service: media_player.volume_set
       data_template:
         entity_id: "{{ sonos_entity }}"
         volume_level: "{{ volume }}"
     - service: tts.amazon_polly_say
       data_template:
         entity_id: "{{ sonos_entity }}"
         message: "{{ message }}"
     - delay: "{{ delay }}"
     - service: sonos.restore
       data_template:
         entity_id: "{{ sonos_entity }}"

  sonos_play:
    alias: "Sonos play script"
    sequence:
     - service: sonos.snapshot
       data_template:
         entity_id: "{{ sonos_entity }}"
     - service: sonos.unjoin
       data_template:
         entity_id: "{{ sonos_entity }}"
     - service: media_player.volume_set
       data_template:
         entity_id: "{{ sonos_entity }}"
         volume_level: "{{ volume }}"
     - service: media_player.play_media
       data_template:
         entity_id: "{{ sonos_entity }}"
         media_content_id: "{{ media_content_id }}"
         media_content_type: "audio/mp3"
     - delay: "{{ delay }}"
     - service: sonos.restore
       data_template:
         entity_id: "{{ sonos_entity }}"

  test_script:
    alias: "test TTS"
    sequence:
     - service: tts.amazon_polly_say
       data_template:
         entity_id: "media_player.office"
         message: "Hola, aquí estoy."    

### Scenes
  patio_lights_scene:
    sequence:
      - service: light.turn_on
        data:
          entity_id: light.entrance  
          brightness: 120
          kelvin: 2000
      - service: light.turn_on
        entity_id: light.patio_strip
      - service: homeassistant.turn_on
        data:
          entity_id: light.front_door
          brightness: 255
          kelvin: 1500
