title: Cuauhtemoc97
views:
  - badges:
      - person.felipe
      - person.teresa
      - sensor.pv_today_kw
      - binary_sensor.192_168_100_51
      - binary_sensor.pressure_falling
    cards:
      - entities:
          - entity: light.entrance
            name: Luces entrada
          - entity: sensor.water_tank_liters
            icon: 'mdi:cup-water'
            name: Cisterna
          - entity: sensor.water_usage_rate_f
            icon: 'mdi:water-pump'
            name: Uso de agua
          - entity: sensor.gas_tank_filtered
            name: Gas LP
            icon: 'mdi:gas-cylinder'
          - entity: cover.street_gate
            name: Portón
        type: entities
      - entities:
          - entity: input_boolean.gate_door_working
            name: Click
            icon: 'mdi:car'
            hold_action: 
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.toggle_gate
          - entity: input_boolean.sleep_mode
            name: Dormir
            tap_action:
              action: toggle
            icon: 'mdi:sleep'
          - entity: light.patio_floodlight
            name: Reflector
            icon: 'mdi:car-parking-lights'
            tap_action:
              action: toggle
        columns: 4
        type: glance
      - entities:
          - entity: input_boolean.auto_light
            name: Auto luces
            icon: 'mdi:flash-outline'
          - entity: media_player.bedroom_apple_tv
            name: Apple TV Recámara
          - entity: media_player.tv_room_apple_tv
            name: Apple TV cuarto Tele
          - entity: media_player.bedroom_tv
            name: Samsung TV
        type: entities
    icon: 'mdi:home'
    path: default_view
    title: Casa
  - badges:
      - sensor.pool_temperature
      - switch.pool_pump
      - timer.pump_run
      - sensor.pool_panel_timer_minutes
    cards:
      - entities:
          - entity: switch.pool_pump
            name: Bomba
          - entity: input_number.pool_run_time
            name: Tiempo
          - entity: input_boolean.pump_auto
            name: Auto alberca
        type: entities
    icon: 'mdi:pool'
    panel: false
    title: Alberca
  - badges:
      - sensor.cuauhtemoc_temp
      - sensor.cuauhtemoc_humidity
    cards:
      - entities:
          - entity: light.garden_lights
            name: Luces Jardín
          - entity: switch.raised_beds_water
            name: Riego camas
            secondary_info: last-changed
          - entity: sensor.cuauhtemoc_daily_rain
            name: Lluvia hoy 2
          - entity: sensor.cumulative_rain_today
            name: Lluvia hoy
            icon: mdi:weather-rainy
          - entity: sensor.cumulative_rain_yesterday
            name: Lluvia ayer
            icon: mdi:weather-rainy
          - entity: sensor.rain_mm_twoday
            name: Lluvia 2 días
            icon: mdi:weather-rainy
        type: entities
      - entity: weather.dark_sky
        type: weather-forecast
    icon: 'mdi:flower'
    title: Jardin
  - badges:
      - sensor.voltage_house
      - sensor.ups_input_voltage
      - sensor.kitchen_lp_gas
      - sensor.bedroom_lp_gas
    cards:
      - entities:
          - entity: binary_sensor.192_168_100_51
            name: Zoneminder
          - entity: sensor.zoneminder_host_cpu_used
            name: ZM cpu
          - entity: sensor.zoneminder_host_ram_free
            name: ZM mem
          - entity: sensor.ups_status
          - entity: sensor.ups_battery
        type: entities
      - entities:
          - entity: binary_sensor.felipe_window
          - entity: binary_sensor.hall_door
          - entity: binary_sensor.kitchen_door
          - entity: binary_sensor.main_bathroom
          - entity: binary_sensor.tita_door
          - entity: binary_sensor.patio_gate
          - entity: binary_sensor.workshop
          - entity: binary_sensor.main_garden_door
        type: entities
      - entities:
          - binary_sensor.motion_bano_principal
          - binary_sensor.motion_bano_visitas
          - binary_sensor.motion_cocina
          - binary_sensor.motion_comedor
          - binary_sensor.motion_estudiof
          - binary_sensor.motion_estudiot
          - binary_sensor.motion_hall_entrada
          - binary_sensor.motion_pasillo_comedor_1
          - binary_sensor.motion_pasillo_recamaras
          - binary_sensor.motion_recamara
          - binary_sensor.motion_sala
          - binary_sensor.motion_terraza
          - binary_sensor.motion_tvroom
          - entity: binary_sensor.ring_front_door_motion
            name: Front gate
          - binary_sensor.motion_camera_escaleras
          - binary_sensor.motion_camera_hall
          - binary_sensor.motion_camera_patio
          - binary_sensor.motion_camera_puerta_patio
        state_filter:
          - 'on'
        type: entity-filter
      - entity: camera.front_door
        type: picture-entity
    icon: 'mdi:shield-home-outline'
    title: Seguridad
  - badges:
      - sensor.ha_db_size
      - binary_sensor.remote_ui
      - sensor.load_1m
    cards:
      - entities:
          - entity: group.all_automations
          - entity: group.all_scripts
          - entity: group.all_lights
        type: entities
      - type: picture-entity
        entity: camera.gas_tank_camera
      - entities:
          - sensor.gas_tank_filtered
          - sensor.gas_tank_raw
          - sensor.water_usage_rate_f
          - sensor.water_usage_rate
          - sensor.water_tank_liters
          - sensor.water_tank_distance_raw
          - sensor.water_tank_distance_filtered
          - sensor.cuauhtemoc_abs_pressure
        hours_to_show: 4
        type: history-graph    
    icon: 'mdi:cogs'
    title: Settings
  - badges:
      - binary_sensor.high_water_usage
      - binary_sensor.patio_doorbell
      - binary_sensor.ring_front_door_motion
      - binary_sensor.ring_front_door_ding
      - binary_sensor.remote_ui
      - person.felipe
      - person.teresa
      - device_tracker.iphonesef
      - device_tracker.iphone_tere
      - sun.sun

    cards:
      - entity: media_player.office
        type: media-control
      - entity: media_player.living_room
        type: media-control
      - entities:
          - input_boolean.dark_house
          - input_boolean.pump_auto
          - input_boolean.gate_door_working
          - input_boolean.gate_state
        title: Input boolean
        type: entities
      - entities:
          - input_number.pool_run_time
        title: Input number
        type: entities
      - entity: media_player.bedroom_tv
        type: media-control
      - entity: media_player.bedroom_apple_tv
        type: media-control
      - entity: media_player.tv_room_apple_tv
        type: media-control
      - entities:
          - remote.bedroom_apple_tv
          - remote.tv_room_apple_tv
        title: Remote
        type: entities
      - entities:
          - switch.raised_beds_water
          - switch.pool_pump
        title: Switch
        type: entities
    icon: 'mdi:trash-can'
    path: ''
    title: Varios
