title: Cuauhtemoc97
views:
  - badges:
      - person.felipe_gonzalez
      - person.teresa
      - sensor.pv_today_kw
      - binary_sensor.xeoma_server
      - binary_sensor.pressure_falling
    cards:
      - entities:
          - entity: light.entrance
            name: Luces entrada
          - entity: sensor.water_tank_liters
            icon: 'mdi:cup-water'
            name: Cisterna
          - entity: sensor.water_usage_rate_f
            icon: 'mdi:water-pump'
            name: Uso de agua
          - entity: sensor.gas_tank_filtered
            name: Gas LP
            icon: 'mdi:gas-cylinder'
          #- entity: cover.street_gate
          #  name: Portón
          #- entity: binary_sensor.ring_front_door_ding
          #  name: Timbre Portón
          #  secondary_info: last-changed
          - entity: binary_sensor.patio_doorbell
            name: Timbre Patio
            secondary_info: last-changed
        type: entities
      - entities:
          - entity: script.toggle_gate
            name: Portón
            icon: 'mdi:car'
            tap_action: 
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.toggle_gate
          - entity: input_boolean.sleep_mode
            name: Dormir
            tap_action:
              action: toggle
            icon: 'mdi:sleep'
          - entity: light.patio_floodlight
            name: Reflector
            icon: 'mdi:car-parking-lights'
            tap_action:
              action: toggle
          - entity: cover.bedroom_blinds_1
            name: Persianas
            tap_action:
              action: toggle
        columns: 4
        type: glance
      - entities:
          - entity: input_boolean.auto_light
            name: Auto luces
          - entity: input_boolean.auto_persianas
            name: Auto persianas
            icon: 'mdi:flash-outline'
          - entity: media_player.bedroom
            name: Apple TV Recámara
          - entity: media_player.family_room_apple_tv_2
            name: Apple TV cuarto Tele
          - entity: media_player.samsung_un55ku6000
            name: Samsung TV
          - entity: script.apagar_luces
            name: Apagar luces
            icon: 'mdi:lightbulb'
            tap_action: 
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.apagar_luces
        type: entities
        show_header_toggle: false
      - entities:
          - entity: cover.bedroom_blinds_1
          - entity: cover.bedroom_blinds_2 
        type: entities
      - type: alarm-panel
        entity: alarm_control_panel.home_alarm
    icon: 'mdi:home'
    path: default_view
    title: Casa
  - badges:
      - sensor.pool_temperature
      - switch.pool_pump
      - timer.pump_run
      - sensor.pool_panel_timer_minutes
    cards:
      - entities:
          - entity: switch.pool_pump
            name: Bomba
          - entity: input_number.pool_run_time
            name: Tiempo
          - entity: input_boolean.pump_auto
            name: Auto alberca
        type: entities
        show_header_toggle: false
      - type: history-graph
        entities:
          - entity: sensor.filtered_pool_temperature
            name: Temperatura salida
          - entity: switch.pool_pump
            name: Bomba
        hours_to_show: 3
    icon: 'mdi:pool'
    panel: false
    title: Alberca
  - badges:
      - sensor.cuauhtemoc_temp
      - sensor.cuauhtemoc_humidity
      - sensor.rain_mm_twoday
      - sensor.cuauhtemoc_hourly_rain_rate
      - weather.dark_sky
    cards:
      - entities:
          - entity: light.garden_lights
            name: Luces Jardín
          - entity: switch.raised_beds_water
            name: Riego camas
            secondary_info: last-changed
          - entity: switch.section_1_water
            name: Zona 1
            secondary_info: last-changed
          - entity: switch.section_2_water
            name: Zona 2
            secondary_info: last-changed
          - entity: switch.pots_water
            name: Macetas
            secondary_info: last-changed
          - entity: sensor.cumulative_rain_today
            name: Lluvia hoy
            icon: mdi:weather-rainy
          - entity: sensor.cumulative_rain_yesterday
            name: Lluvia ayer
            icon: mdi:weather-rainy
        type: entities
      - entity: weather.dark_sky
        type: weather-forecast
      - entities: 
          - entity: sensor.cuauhtemoc_hourly_rain_rate
            name: In lluvia por hora
        hours_to_show: 72
        type: history-graph
    icon: 'mdi:flower'
    title: Jardin
  - badges:
      - sensor.ups_input_voltage
      - sensor.kitchen_lp_gas
      - sensor.bedroom_lp_gas
    cards:
      - entities:
          - entity: binary_sensor.ups_online_status
            name: Xeoma server
          - entity: sensor.xeoma_host_cpu_used_2
            name: Xeoma cpu
          - entity: sensor.xeoma_host_ram_free_2
            name: Xeoma free mem
          - entity: sensor.ups_status
          - entity: sensor.ups_battery
        type: entities
      - entities:
          - entity: binary_sensor.felipe_window
          #- entity: binary_sensor.wyzesense_7780f668
          - entity: binary_sensor.puerta_hall
            name: puerta de sala
          - entity: binary_sensor.oficina_tere
          - entity: binary_sensor.downstairs_bathroom
            name: baño oficinas
          - entity: binary_sensor.kitchen_door
          - entity: binary_sensor.main_bathroom
            name: baño principal
          - entity: binary_sensor.tita_door
          - entity: binary_sensor.patio_gate
          - entity: binary_sensor.workshop
          - entity: binary_sensor.main_garden_door
        type: entities
      - entities:
          - binary_sensor.motion_bano_principal
          - binary_sensor.motion_bano_visitas
          - binary_sensor.motion_cocina
          - binary_sensor.motion_comedor
          - binary_sensor.motion_estudiof
          - binary_sensor.motion_estudiot
          - binary_sensor.movimiento_hall
          - binary_sensor.motion_pasillo_comedor_1
          - binary_sensor.motion_pasillo_recamaras
          - binary_sensor.motion_recamara
          - binary_sensor.motion_vestidor
          - binary_sensor.motion_sala
          - binary_sensor.motion_terraza
          - binary_sensor.motion_tvroom
          - entity: binary_sensor.front_door_motion
            name: Front gate
          - binary_sensor.motion_camera_escaleras
          - binary_sensor.motion_camera_hall
          - binary_sensor.motion_camera_patio
          - binary_sensor.motion_camera_puerta_patio
        #state_filter:
        #  - 'on'
        type: entities
      - entity: camera.front_door
        type: picture-entity
      - type: picture-entity
        entity: camera.entrada_personas
      - type: picture-entity
        entity: camera.patio_personas
      - type: picture-entity
        entity: camera.huerto_personas
      - type: picture-entity
        entity: camera.oficina_personas
    icon: 'mdi:shield-home-outline'
    title: Seguridad

  - title: Clima
    icon: 'mdi:air-conditioner'
    cards:
      - type: thermostat
        entity: climate.ac_recamara
      - type: thermostat
        entity: climate.ac_tita
      - type: history-graph
        title: Temperatura
        hours_to_show: 4
        entities:
          - entity: sensor.tv_room_temperature
            name: Cuarto TV
          - entity: sensor.bedroom_temperature
            name: Cuarto principal
          - entity: sensor.living_room_temperature
            name: Sala
          - entity: sensor.kitchen_temperature  
            name: Cocina
          - entity:  sensor.cuauhtemoc_inside_temp
            name: Alberca
      - type: history-graph
        title: Humedad
        hours_to_show: 4
        entities:
          - entity: sensor.cuauhtemoc_humidity_in
            name: Hall
          - entity: sensor.kitchen_humidity
            name: Cocina
          - entity: sensor.living_room_humidity
            name: Sala

  - cards:
      - entity: media_player.office
        type: media-control
      - entity: media_player.living_room
        type: media-control
      - entity: media_player.samsung_un55ku6000
        type: media-control
      - entity: media_player.bedroom
        type: media-control
      - entity: media_player.family_room_apple_tv_2
        type: media-control
    icon: 'mdi:music'
    title: Media


  - badges:
      - sensor.ha_db_size
      - binary_sensor.remote_ui
      - sensor.load_1m
      - sensor.voltage_dryer
      - sensor.voltage_washer
      - timer.kettle_timer

    cards:
# Example entities card configuration
      # - type: entities
      #   entities:
      #   - type: cast
      #     name: Jardin
      #     # The path of the view (or number)
      #     view: 2
      #     hide_if_unavailable: true
      - type: picture-entity
        entity: camera.gas_tank_camera
      - entities:
          - sensor.gas_tank_filtered
          - sensor.gas_tank_raw
          - sensor.water_usage_rate_f
          - sensor.water_usage_rate
          - sensor.felipe_study_photo_level
        hours_to_show: 4
        type: history-graph

      - entities:
          - sensor.dryer
          - sensor.washing_machine
          - sensor.washing_machine_stats_mean
          - sensor.living_photo_level
          - sensor.cuauhtemoc_solar_rad
          - sensor.cuauhtemoc_solar_rad_lx
        hours_to_show: 6
        type: history-graph
      - entities:
          - input_boolean.dark_house
          - input_boolean.pump_auto
          - input_boolean.gate_door_working
          - input_boolean.gate_state
          - input_boolean.washing_machine_cycle
          - input_boolean.washing_machine_high
          - input_boolean.dryer_cycle
          - input_boolean.dryer_high
        title: Input boolean
        type: entities    
    icon: 'mdi:cogs'
    title: Settings
    

