title: Cuauhtemoc97
views:
  - badges:
      - person.felipe_gonzalez
      - person.teresa
      - sensor.pv_today_kw
      - binary_sensor.192_168_100_51
      - binary_sensor.pressure_falling
    cards:
      - entities:
          - entity: light.entrance
            name: Luces entrada
          - entity: sensor.water_tank_liters
            icon: 'mdi:cup-water'
            name: Cisterna
          - entity: sensor.water_usage_rate_f
            icon: 'mdi:water-pump'
            name: Uso de agua
          - entity: sensor.gas_tank_filtered
            name: Gas LP
            icon: 'mdi:gas-cylinder'
          - entity: cover.street_gate
            name: Portón
          - entity: binary_sensor.ring_front_door_ding
            name: Timbre Portón
            secondary_info: last-changed
        type: entities
      - entities:
          - entity: script.toggle_gate
            name: Click
            icon: 'mdi:car'
            tap_action: 
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.toggle_gate
          - entity: input_boolean.sleep_mode
            name: Dormir
            tap_action:
              action: toggle
            icon: 'mdi:sleep'
          - entity: light.patio_floodlight
            name: Reflector
            icon: 'mdi:car-parking-lights'
            tap_action:
              action: toggle
          - entity: cover.bedroom_blinds_1
            name: Persianas
            tap_action:
              action: toggle
        columns: 4
        type: glance
      - entities:
          - entity: input_boolean.auto_light
            name: Auto luces
            icon: 'mdi:flash-outline'
          - entity: media_player.bedroom_apple_tv
            name: Apple TV Recámara
          - entity: media_player.tv_room_apple_tv
            name: Apple TV cuarto Tele
          - entity: media_player.bedroom_tv
            name: Samsung TV
        type: entities
      - entities:
          - entity: cover.bedroom_blinds_1
          - entity: cover.bedroom_blinds_2 
        type: entities
      - type: alarm-panel
        entity: alarm_control_panel.home_alarm
    icon: 'mdi:home'
    path: default_view
    title: Casa
  - badges:
      - sensor.pool_temperature
      - switch.pool_pump
      - timer.pump_run
      - sensor.pool_panel_timer_minutes
    cards:
      - entities:
          - entity: switch.pool_pump
            name: Bomba
          - entity: input_number.pool_run_time
            name: Tiempo
          - entity: input_boolean.pump_auto
            name: Auto alberca
        type: entities
      - type: history-graph
        entities:
          - entity: sensor.pool_temperature
            name: Temperatura salida
          - entity: switch.pool_pump
            name: Bomba
        hours_to_show: 6
    icon: 'mdi:pool'
    panel: false
    title: Alberca
  - badges:
      - sensor.cuauhtemoc_temp
      - sensor.cuauhtemoc_humidity
      - sensor.rain_mm_twoday
      - sensor.cuauhtemoc_hourly_rain_rate
      - weather.dark_sky
    cards:
      - entities:
          - entity: light.garden_lights
            name: Luces Jardín
          - entity: switch.raised_beds_water
            name: Riego camas
            secondary_info: last-changed
          - entity: switch.section_1_water
            name: Zona 1
            secondary_info: last-changed
          - entity: switch.section_2_water
            name: Zona 2
            secondary_info: last-changed
          - entity: switch.pots_water
            name: Macetas
            secondary_info: last-changed
          - entity: sensor.cuauhtemoc_daily_rain
            name: Lluvia hoy 2
          - entity: sensor.cumulative_rain_today
            name: Lluvia hoy
            icon: mdi:weather-rainy
          - entity: sensor.cumulative_rain_yesterday
            name: Lluvia ayer
            icon: mdi:weather-rainy
        type: entities
      - entity: weather.dark_sky
        type: weather-forecast
      - entities: 
          - entity: sensor.cuauhtemoc_hourly_rain_rate
            name: In lluvia por hora
        hours_to_show: 72
        type: history-graph
    icon: 'mdi:flower'
    title: Jardin
  - badges:
      - sensor.ups_input_voltage
      - sensor.kitchen_lp_gas
      - sensor.bedroom_lp_gas
    cards:
      - entities:
          - entity: binary_sensor.192_168_100_51
            name: Zoneminder
          - entity: sensor.zoneminder_host_cpu_used
            name: ZM cpu
          - entity: sensor.zoneminder_host_ram_free
            name: ZM mem
          - entity: sensor.ups_status
          - entity: sensor.ups_battery
        type: entities
      - entities:
          - entity: binary_sensor.felipe_window
          - entity: binary_sensor.hall_door
          - entity: binary_sensor.kitchen_door
          - entity: binary_sensor.main_bathroom
          - entity: binary_sensor.tita_door
          - entity: binary_sensor.patio_gate
          - entity: binary_sensor.workshop
          - entity: binary_sensor.main_garden_door
        type: entities
      - entities:
          - binary_sensor.motion_bano_principal
          - binary_sensor.motion_bano_visitas
          - binary_sensor.motion_cocina
          - binary_sensor.motion_comedor
          - binary_sensor.motion_estudiof
          - binary_sensor.motion_estudiot
          - binary_sensor.motion_hall_entrada
          - binary_sensor.motion_pasillo_comedor_1
          - binary_sensor.motion_pasillo_recamaras
          - binary_sensor.motion_recamara
          - binary_sensor.motion_sala
          - binary_sensor.motion_terraza
          - binary_sensor.motion_tvroom
          - entity: binary_sensor.ring_front_door_motion
            name: Front gate
          - binary_sensor.motion_camera_escaleras
          - binary_sensor.motion_camera_hall
          - binary_sensor.motion_camera_patio
          - binary_sensor.motion_camera_puerta_patio
        #state_filter:
        #  - 'on'
        type: entities
      - entity: camera.front_door
        type: picture-entity
      - type: picture-entity
        entity: camera.entrada_personas
      - type: picture-entity
        entity: camera.patio_personas
      - type: picture-entity
        entity: camera.huerto_personas
      - type: picture-entity
        entity: camera.oficina_personas
    icon: 'mdi:shield-home-outline'
    title: Seguridad

  - title: Clima
    icon: 'mdi:air-conditioner'
    cards:
      - type: history-graph
        title: Temperatura
        entities:
          - entity: sensor.tv_room_temperature
            name: Cuarto TV
          - entity: sensor.bedroom_temperature
            name: Cuarto principal
          - entity: sensor.living_room_temperature
            name: Sala
          - entity: sensor.kitchen_temperature  
            name: Cocina
          - entity: sensor.pool_temperature  
            name: Alberca
      - type: history-graph
        title: Humedad
        entities:
          - entity: sensor.cuauhtemoc_humidity_in
            name: Hall
          - entity: sensor.kitchen_humidity
            name: Cocina
          - entity: sensor.living_room_humidity
            name: Sala

  - cards:
      - entity: media_player.office
        type: media-control
      - entity: media_player.living_room
        type: media-control
      - entity: media_player.bedroom_tv
        type: media-control
      - entity: media_player.bedroom_apple_tv
        type: media-control
      - entity: media_player.tv_room_apple_tv
        type: media-control
      - entities:
          - remote.bedroom_apple_tv
          - remote.tv_room_apple_tv
        title: Remote
        type: entities
    icon: 'mdi:music'
    title: Media


  - badges:
      - sensor.ha_db_size
      - binary_sensor.remote_ui
      - sensor.load_1m
    cards:
      - entities:
          - entity: group.all_automations
          - entity: group.all_scripts
          - entity: group.all_lights
        type: entities
      - type: picture-entity
        entity: camera.gas_tank_camera
      - entities:
          - sensor.gas_tank_filtered
          - sensor.gas_tank_raw
          - sensor.water_usage_rate_f
          - sensor.water_usage_rate
          - sensor.water_tank_distance_raw
          - sensor.water_tank_distance_filtered
        hours_to_show: 4
        type: history-graph
      - entities:
          - input_boolean.dark_house
          - input_boolean.pump_auto
          - input_boolean.gate_door_working
          - input_boolean.gate_state
        title: Input boolean
        type: entities    
    icon: 'mdi:cogs'
    title: Settings
    

