version: '3'

services:
    appdaemon:
      container_name: appdaemon
      image: acockburn/appdaemon:latest
      env_file:
        - appd.env
      ports:
        - 5050:5050
      volumes:
        -  ./appdaemon/config:/conf

    casa_app:
      container_name: casa_app
      image: connectors/casa-app:latest
      ports:
        - 8090:8090
    # node-red:
    #   container_name: nodered
    #   image: nodered/node-red-docker:v8
    #   volumes:
    #     - ./node-red-data:/data
    #   ports:
    #     - 1880:1880
