
#Installer:
#  class: DepeInstaller
#  module: installer
#  priority: 1

Motion Lights:
  class: MotionLights
  module: motion_lights_s
  constrain_input_boolean: input_boolean.dark_house
  grouping: >
    {"vestidor":{"sensors":["binary_sensor.motion_vestidor"],"lights": "light.dressing_room", "delay":120, "use_sleep":"dim"},
    "bano_visitas":{"sensors":["binary_sensor.motion_bano_visitas"],"lights": "light.bano_visitas_gp", "delay":240, "use_sleep":"no"},
    "sala":{"sensors":["binary_sensor.motion_sala"],"lights":"light.luces_de_sala", "delay":240, "use_sleep":"no"},
    "bano_principal":{"sensors":["binary_sensor.motion_bano_principal"],"lights":"light.bano_principal","delay":240, "use_sleep":"dim"},
    "cocina":{"sensors":["binary_sensor.motion_cocina"],"lights":"light.luces_de_la_cocina","delay":240, "use_sleep":"no"},
    "comedor":{"sensors":["binary_sensor.motion_comedor"],"lights":"light.comedor","delay":240, "use_sleep":"no"},
    "estudiof":{"sensors":["binary_sensor.motion_estudiof", "binary_sensor.felipe_oficina_ocupada" ],"lights":"light.oficina_de_felipe","delay":600, "use_sleep":"no", "occupancy":"felipe_office_occupancy"},
    "estudiot":{"sensors":["binary_sensor.motion_estudiot"],"lights":"light.study_tere","delay":300, "use_sleep":"no"},
    "hall":{"sensors":["binary_sensor.movimiento_hall"],"lights":"light.luces_del_hall_de_entrada","delay":120, "use_sleep":"dim"},
    "pasillo":{"sensors":["binary_sensor.motion_pasillo_comedor_1","binary_sensor.motion_pasillo_comedor_2"],"lights":"light.pasillo_del_comedor","delay":60, "use_sleep":"dim", "brightness":250},
    "pasillorec":{"sensors":["binary_sensor.motion_pasillo_recamaras"],"lights":"light.pasillo_recamaras","delay":30, "use_sleep":"dim", "brightness":250},
    "recamara":{"sensors":["binary_sensor.motion_recamara","binary_sensor.cabecera_recamara"],"lights":"light.recamara_principal",  "delay":500, "use_sleep":"dark", "media":"media_player.bedroom"},
    "terraza":{"sensors":["binary_sensor.motion_terraza"],"lights":"light.terraza_de_jardin","delay":240, "use_sleep":"no"},
    "tvroom":{"sensors":["binary_sensor.motion_tvroom"],"lights":"light.tv_room","delay":180, "use_sleep":"dark", "media": "media_player.family_room_apple_tv_2"}}



Sound:
  base: media
  class: Sound
  ip: 192.168.100.50
  module: sound
  base: sounds
  player: media_player.living_room
  port: '8123'

Gas Tank Reader:
  class: GasTankReader
  module: gas_tank_reader
  constrain_start_time: "09:00:00"
  constrain_end_time: "19:00:00"
Grandfather:
  class: Grandfather
  dependencies:
    - Sound
  end_time: '21:01:00'
  media: GFChime
  module: grandfather
  #mute_if_home: device_tracker.dedb5e711a24415baaae5cf8e880d852
  player: media_player.living_room
  start_time: 07:59:00
  volume: '0.5'

Solar Panels:
  class: APSystems
  module: ap_systems
  ecu_id: "216000005669"

Door Sensors:
  class: DoorSensors
  module: door_sensors
  rf_bridge: "sensor.rf_bridge_result"
  codes: >
    {"FBE86":"door_window/felipe_study",
     "F6946":"door_window/tita_door",
     "70186":"door_window/main_bath",
     "F5D86":"door_window/workshop_door",
     "B95BA":"door_window/main_garden_door",
     "AA246":"door_window/kitchen_door",
     "AF006":"door_window/downstairs_bath"}
