appdaemon:
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  time_zone: America/Mexico_City
  plugins:
    HASS:
      type: hass
      ha_url: http://192.168.100.50:8123
      token: !secret token
http:
  url: http://192.168.100.50:5050

api:

admin:
  title: appdaemon