- alias: Raised beds timer
  trigger:
    platform: state
    entity_id: switch.raised_beds_water
    to: 'on'
  action:
  - delay: 00:40:00
  - service: homeassistant.turn_off
    data:
      entity_id: switch.raised_beds_water
  id: c2949b9be5694f27b737eacd3f49b6de