- alias: Voltage alarm
  trigger:
  - platform: numeric_state
    entity_id: sensor.voltage_house
    below: 90
  action:
  - service: notify.iphone_tyf
    data:
      message: La casa está sufriendo de voltaje bajo.

# UPS Automation
- id: UPS_01
  alias: 'Notify when UPS goes on battery'
  trigger:
    - platform: state
      entity_id: sensor.ups_status
      from: 'ONLINE'
      to: 'ONBATT'
  action:
    - service: notify.iphone_tyf
      data:
        title: "Alerta de HomeAssistant"
        message: "Sistema de casa usando batería."