- id: 08887389592
  alias: busy washing machine
  trigger:
    platform: template
    value_template: '{{ states.sensor.washing_machine_stats_mean.attributes.median | float > 50 }}'
  action:
  - service: homeassistant.turn_on
    data:
      entity_id: input_boolean.washing_machine_high
  - service: homeassistant.turn_on
    data:
      entity_id: input_boolean.washing_machine_cycle

- id: 0888738959222156
  alias: idle washing machine
  trigger:
    platform: template
    value_template: '{{ states.sensor.washing_machine_stats_mean.attributes.median | float < 2 }}'
  action:
  - service: homeassistant.turn_off
    data:
      entity_id: input_boolean.washing_machine_high
      
- id: 0888738959211
  alias: notify washing machine
  trigger:
    platform: state
    entity_id: input_boolean.washing_machine_high
    to: 'off'
    for:
      minutes: 5
  action:
  - service: homeassistant.turn_off
    data:
      entity_id: input_boolean.washing_machine_cycle
  - service: notify.slackbot
    data:
      message: Terminó el ciclo de la lavadora.
  - service: script.sonos_say
    data:
      sonos_entity: media_player.living_room
      volume: 0.9
      delay: 00:00:10
      message: La lavadora terminó su ciclo.