climate:
  - platform: smartir
    name: AC recamara
    unique_id: ac_recamara
    device_code: 1062
    controller_data: 192.168.100.59
    temperature_sensor: sensor.bedroom_temperature
  - platform: smartir
    name: AC Tita
    unique_id: ac_tita
    device_code: 1062
    controller_data: 192.168.100.74

sensor:  
  - platform: mqtt
    name: TV room temperature 
    state_topic: "caja_tv/temperature"
    unit_of_measurement: "째C"
    value_template: '{{ value | round(1) }}'
  - platform: mqtt
    name: Living room temperature
    state_topic: "xbeebox/sala/temperature/1/cajasala"
    unit_of_measurement: "째C"
    value_template: '{{ value | round(1) }}'
  - platform: mqtt
    name: Bedroom temperature 
    state_topic: "xbeebox/recamara_principal/temperature/1/cajarecamara"
    unit_of_measurement: "째C"
    value_template: '{{ value | round(1) }}'
  - platform: mqtt
    name: Kitchen temperature 
    state_topic: "xbeebox/cocina/temperature/1/cajacocina"
    unit_of_measurement: "째C"
    value_template: '{{ value | round(1) }}'
  - platform: mqtt
    name: Kitchen humidity 
    state_topic: "xbeebox/cocina/humidity/1/cajacocina"
    unit_of_measurement: "%"
    value_template: '{{ value | round(1) }}'
  - platform: mqtt
    name: Living Room humidity 
    state_topic: "xbeebox/sala/humidity/1/cajasala"
    unit_of_measurement: "%"
    value_template: '{{ value | round(1) }}'

## Pressure
  - platform: mqtt
    name: pressure 
    state_topic: "xbeebox/pasillo_comedor/pressure/1/caja_pasillo_comedor"
    unit_of_measurement: "hPa"

automation:
  - alias: "Empezar a enfriar cuarto"
    id: climate11rec
    trigger:
      - platform: time
        at: "19:30:00"
    condition:
      condition: numeric_state
      entity_id: "sensor.bedroom_temperature"
      above: 24
    action:
      - service: climate.set_temperature
        data:
          entity_id: climate.ac_recamara
          hvac_mode: cool
          temperature: 20
