switch:
  - platform: mqtt
    name: "Raised beds water"
    command_topic: "xbeebox/caja_goteo/pin/D2"
    payload_on: "1"
    payload_off: "0"
  - platform: command_line
    switches:
      section_2_water:
        command_on: "/usr/bin/curl -X GET http://192.168.100.159/pasto?command=turn_on&tiempo=30"
        command_off: "/usr/bin/curl -X GET http://192.168.100.159/pasto?command=turn_off"
        command_state: "/usr/bin/curl -X GET http://192.168.100.159/status"
        value_template: '{{ value_json["values"].pasto.state == 1}}'
      section_1_water:
        command_on: "/usr/bin/curl -X GET http://192.168.100.159/jardinera?command=turn_on&tiempo=40"
        command_off: "/usr/bin/curl -X GET http://192.168.100.159/jardinera?command=turn_off"
        command_state: "/usr/bin/curl -X GET http://192.168.100.159/status"
        value_template: '{{ value_json["values"].jardinera.state == 1}}'
      pots_water:
        command_on: "/usr/bin/curl -X GET http://192.168.100.159/macetas?command=turn_on&tiempo=30"
        command_off: "/usr/bin/curl -X GET http://192.168.100.159/macetas?command=turn_off"
        command_state: "/usr/bin/curl -X GET http://192.168.100.159/status"
        value_template: '{{ value_json["values"].macetas.state == 1}}'

binary_sensor:
  - platform: template
    sensors:
      wet_soil:
        entity_id: sensor.rain_mm_twoday
        #value_template: '{{ (5.6*(2120-10*(states.sensor.distancia_cisterna_filtrada.state | float))) | int - 500 }}'
        value_template: "{{ states('sensor.rain_mm_twoday') > 25.0 }}"

automation:
  - alias: Raised beds timer
    trigger:
      platform: state
      entity_id: switch.raised_beds_water
      to: 'on'
    action:
    - delay: 00:45:00
    - service: homeassistant.turn_off
      data:
        entity_id: switch.raised_beds_water
    id: c2949b9be5694f27b737eacd3f49b6de

  - alias: Auto water raised beds
    trigger:
      platform: time
      at: 06:00:00
    condition:
      - condition: time
        weekday:
        - tue
        - thu
        - sat
        - sun
      - condition: numeric_state
        entity_id: sensor.water_tank_liters
        above: 3000
      - condition: state
        entity_id: binary_sensor.wet_soil
        state: 'off'
    action:
      - service: homeassistant.turn_on
        entity_id: switch.raised_beds_water
    id: autovegetable01342001

