image_processing:
  - platform: tensorflow
    source:
      - entity_id: camera.hall_entrada
      - entity_id: camera.huerto
      - entity_id: camera.oficina7
      - entity_id: camera.patio
    file_out:
      - "/Volumes/SSD2/tmp_image_recog/{{ camera_entity.split('.')[1] }}_latest.jpg"
      - "/Volumes/SSD2/tmp_image_recog/{{ camera_entity.split('.')[1] }}_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
    scan_interval: 20
    model:
      graph: /Volumes/SSD2/hass-cuauhtemoc97/homeassistant/config/tensorflow/better_frozen_inference_graph.pb
      categories:
        - person

camera:
  - platform: local_file
    name: Entrada personas
    file_path: /Volumes/SSD2/tmp_image_recog/hall_entrada_latest.jpg
  - platform: local_file
    name: Patio personas
    file_path: /Volumes/SSD2/tmp_image_recog/patio_latest.jpg
  - platform: local_file
    name: Huerto personas
    file_path: /Volumes/SSD2/tmp_image_recog/huerto_latest.jpg
  - platform: local_file
    name: Oficina personas
    file_path: /Volumes/SSD2/tmp_image_recog/oficina7_latest.jpg

sensor:
  - platform: template
    sensors:
      hall_occupancy:
        value_template: >
          {% if states.image_processing.tensorflow_hall_entrada.attributes.summary.person is defined %}
            {{ states.image_processing.tensorflow_hall_entrada.attributes.summary.person | int }}
          {% else %}
              0
          {% endif %}
        unit_of_measurement: "Persons"
      felipe_office_occupancy:
        value_template: >
          {% if states.image_processing.tensorflow_oficina7.attributes.summary.person is defined %}
            {{ states.image_processing.tensorflow_oficina7.attributes.summary.person | int }}
          {% else %}
              0
          {% endif %}
        unit_of_measurement: "Persons"      
      huerto_occupancy:
        value_template: >
          {% if states.image_processing.tensorflow_huerto.attributes.summary.person is defined %}
            {{ states.image_processing.tensorflow_huerto.attributes.summary.person | int }}
          {% else %}
              0
          {% endif %}
        unit_of_measurement: "Persons"    

automation:
#image processing scans
  - id: cam1222345
    alias: scan cam hall
    trigger:
      platform: state
      entity_id: binary_sensor.motion_camera_hall
      to: 'on'
    action:
    - service: image_processing.scan
      data:
        entity_id: image_processing.tensorflow_hall_entrada
  - id: cam1222345
    alias: scan cam patio
    trigger:
      platform: state
      entity_id: binary_sensor.motion_camera_subpatio
      to: 'on'
    action:
    - service: image_processing.scan
      data:
        entity_id: image_processing.tensorflow_patio
  - id: cam1222345
    alias: scan cam huerto
    trigger:
      platform: state
      entity_id: binary_sensor.motion_camera_huerto
      to: 'on'
    action:
    - service: image_processing.scan
      data:
        entity_id: image_processing.tensorflow_huerto