
camera:
  - platform: xeoma
    host: http://192.168.100.51:10090
  - platform: local_file
    name: oficina
    file_path: /Volumes/SSD2/hass-cuauhtemoc97/homeassistant/config/www/snap_oficina.jpg


homeassistant:
  customize:
    binary_sensor.192_168_100_51:
      friendly_name: Xeoma Server
    sensor.zoneminder_host_cpu_used:
      friendly_name: Xeoma CPU

sensor:
# Gas lp
  - platform: mqtt
    name: Kitchen LP gas 
    state_topic: "xbeebox/cocina/gaslpg/1/cajacocina"
    unit_of_measurement: "V"
  - platform: mqtt
    name: Bedroom LP gas 
    state_topic: "xbeebox/recamara_principal/gaslpg/1/cajarecamara"
    unit_of_measurement: "V"
  - platform: command_line
    name: snap_oficina
    command: !secret wyzecam1
    scan_interval: 30

binary_sensor:
  - platform: template
    sensors:
      gas_alto:
        friendly_name: "Nivel de gas alto"
        device_class: gas
        value_template: "{{states('sensor.kitchen_lp_gas')|float > 300 }}"

  - platform: mqtt
    state_topic: "caja_tv/motion"
    name: motion_tvroom
    payload_on: "1"
    payload_off: "0"
    device_class: motion
    off_delay: 60

  - platform: mqtt
    state_topic: "xbeebox/jardin/motion/1/caja_terraza"
    name: motion_terraza
    payload_on: True
    payload_off: False
    device_class: motion
    off_delay: 60

  - platform: mqtt
    name: motion_sala
    state_topic: "xbeebox/sala/motion/1/cajasala"
    payload_on: True
    payload_off: False
    device_class: motion
    off_delay: 30
  - platform: mqtt
    state_topic: "xbeebox/estudiof/motion/1/caja_estudiof"
    name: motion_estudiof
    payload_on: True
    payload_off: False
    device_class: motion
  - platform: mqtt
    #state_topic: "xbeebox/estudiot/motion/1/caja_estudiot"
    state_topic: "ha_slave/movimiento_oficina_tere"
    name: motion_estudiot
    payload_on: "on"
    payload_off: "off"
    device_class: motion
  - platform: mqtt
    state_topic: "xbeebox/recamara_principal/motion/1/cajarecamara"
    name: motion_recamara
    payload_on: True
    payload_off: False
    device_class: motion
    off_delay: 45
  - platform: mqtt
    name: motion_pasillo_recamaras
    state_topic: "xbeebox/pasillo_recamaras/samples/caja_pasillo_recamaras"
    payload_off: False
    payload_on: True
    device_class: motion
    value_template: '{{ value_json[0]["dio-4"] }}'
    off_delay: 10
  - platform: mqtt
    name: motion_vestidor
    state_topic: "xbeebox/vestidor/samples/caja_vestidor"
    payload_off: False
    payload_on: True
    device_class: motion
    value_template: '{{ value_json[0]["dio-2"] }}'
    off_delay: 10
  - platform: mqtt
    name: motion_bano_visitas
    state_topic: "xbeebox/bano_visitas/samples/caja_bano_visitas"
    payload_off: False
    payload_on: True
    value_template: '{{ value_json[0]["dio-1"] }}'
    device_class: motion
    off_delay: 60

  - platform: mqtt
    name: motion_hall_entrada_old
    state_topic: "xbeebox/hall_entrada/samples/caja_puerta"
    payload_off: False
    payload_on: True
    value_template: '{{ value_json[0]["dio-1"] }}'
    device_class: motion
    off_delay: 10
  - platform: mqtt
    name: movimiento hall
    state_topic: 'ha_slave/movimiento_hall'
    payload_off: 'off'
    payload_on: 'on'
    device_class: motion

  - platform: mqtt
    name: motion_bano_principal
    state_topic: "xbeebox/bano_principal/samples/caja_bano_principal"
    payload_off: False
    payload_on: True
    value_template: '{{ value_json[0]["dio-1"] }}'
    device_class: motion
    off_delay: 10

  - platform: mqtt
    name: motion_pasillo_comedor_1
    state_topic: "xbeebox/pasillo_comedor/motion/1/caja_pasillo_comedor"
    payload_on: True
    payload_off: False
    device_class: motion
    off_delay: 10
  - platform: mqtt
    name: motion_pasillo_comedor_2
    state_topic: "xbeebox/pasillo_comedor/motion/2/caja_pasillo_comedor"
    payload_on: True
    payload_off: False
    device_class: motion
    off_delay: 10
  - platform: mqtt
    name: motion_comedor
    state_topic: "xbeebox/comedor/motion/1/caja_comedor"
    payload_on: True
    payload_off: False
    device_class: motion
    off_delay: 60

  - platform: mqtt
    name: motion_cocina
    state_topic: "xbeebox/cocina/motion/1/cajacocina"
    payload_on: True
    payload_off: False
    device_class: motion
    off_delay: 30
  - platform: mqtt
    name: motion_tita
    state_topic: "xbeebox/cuarto_teresita/motion/1/caja_teresita"
    payload_on: True
    payload_off: False
    device_class: motion
    off_delay: 30

## Camera motion
  - platform: mqtt
    name: motion_camera_hall
    state_topic: "xeoma_server/camera_hall"
    # value_template: '{{ "ON" }}'
    # value_template: '{{ "OFF" }}'
    device_class: motion
  - platform: mqtt
    name: motion_camera_patio_door
    state_topic: "xeoma_server/camera_patio_door"
    # value_template: '{{ "ON" }}'
    # value_template: '{{ "OFF" }}'
    device_class: motion
  - platform: mqtt
    name: motion_camera_patio_dome
    state_topic: "xeoma_server/camera_patio_dome"
    # value_template: '{{ "ON" }}'
    # value_template: '{{ "OFF" }}'
    device_class: motion
  - platform: mqtt
    name: motion_camera_escaleras
    state_topic: "xeoma_server/camera_escalera"
    # value_template: '{{ "ON" }}'
    # value_template: '{{ "OFF" }}'
    device_class: motion
  - platform: mqtt
    name: motion_camera_huerto_camas
    state_topic: "xeoma_server/camera_huerto_camas"
    off_delay: 30

  ## Doors and windows
  - platform: mqtt
    name: Felipe window
    state_topic: door_window/felipe_study
    payload_on: "open"
    payload_off: "closed"
    device_class: window
  - platform: mqtt
    name: Kitchen door
    state_topic: door_window/kitchen_door
    payload_on: "open"
    payload_off: "closed"
    device_class: door
  - platform: mqtt
    name: Tita door
    state_topic: door_window/tita_door
    payload_on: "open"
    payload_off: "closed"
    device_class: door
  - platform: mqtt
    name: Main Garden door
    state_topic: door_window/main_garden_door
    payload_on: "open"
    payload_off: "closed"
    device_class: door
  - platform: mqtt
    name: Main Bathroom
    state_topic: door_window/main_bath
    payload_on: "open"
    payload_off: "closed"
    device_class: door
  - platform: mqtt
    name: Workshop
    state_topic: door_window/workshop_door
    payload_on: "open"
    payload_off: "closed"
    device_class: door
  - platform: mqtt
    name: Downstairs Bathroom
    state_topic: "door_window/downstairs_bath"
    payload_on: "open"
    payload_off: "closed"
    device_class: door
  - platform: mqtt
    name: Hall door old
    state_topic: "xbeebox/hall_entrada/samples/caja_puerta"
    payload_off: True
    payload_on: False
    value_template: '{{ value_json[0]["dio-2"] }}'
    device_class: door
  - platform: mqtt
    name: puerta hall
    state_topic: 'ha_slave/puerta_hall'
    payload_off: 'off'
    payload_on: 'on'
    device_class: door
  - platform: mqtt
    name: oficina Tere
    state_topic: 'ha_slave/puerta_oficina_tere'
    payload_off: 'off'
    payload_on: 'on'
    device_class: door
  - platform: mqtt
    name: cabecera_recamara
    state_topic: 'ha_slave/recamara_cabecera'
    payload_off: 'off'
    payload_on: 'on'
    device_class: motion

input_boolean:
  high_temperature:
    name: "High temperature"
    initial: off

automation:
  - alias: Tita door notification
    trigger:
      platform: state
      entity_id: binary_sensor.tita_door
      from: 'off'
      to: 'on'
    action:
    - service: script.sonos_play
      data:
        sonos_entity: media_player.living_room
        volume: 0.9
        delay: 00:00:06
        media_content_id: http://192.168.100.50:8123/local/sounds/meow1.mp3
    id: 433743d713c7427c9b456c8aff12cf8b

  ## Notification of opered door at night
  - alias: Tita door notification message
    trigger:
      platform: state
      entity_id: binary_sensor.tita_door
      from: 'off'
      to: 'on'
    condition:
      condition: time
      after: '22:00:00'
      before: 06:00:00
    action:
    - service: notify.iphone_tyf
      data:
        message: La puerta de Tita se abrió!


  - alias: Hign temperatures
    trigger:
      platform: numeric_state
      entity_id:
        - sensor.tv_room_temperature
        - sensor.bedroom_temperature
        - sensor.living_room_temperature
        - sensor.kitchen_temperature
      above: 40.0
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.high_temperature_indoor
      - service: script.sonos_say
        data:
          sonos_entity: media_player.living_room
          volume: 0.9
          delay: 00:00:10
          message: Temperaturas demasiado altas
  - alias: Gas Alto automation
    trigger:
      platform: numeric_state
      entity_id: sensor.kitchen_lp_gas
      above: 380
    action:
      - service: script.sonos_say
        data:
          sonos_entity: media_player.living_room
          volume: 0.9
          delay: 00:00:10
          message: Alarma de gas en cocina

  - alias: Raised beds notification
    trigger:
      platform: state
      entity_id: binary_sensor.motion_camera_huerto_camas
      to: 'on'
    condition:
      - condition: numeric_state
        entity_id: sensor.cuauhtemoc_hourly_rain_rate
        below: 0.20
      - condition: numeric_state
        entity_id: image_processing.tensorflow_patio_door
        below: 1
    action:
    - service: camera.snapshot
      data:
        entity_id: camera.patio_door
        filename: "/Volumes/SSD2/hass-cuauhtemoc97/homeassistant/config/www/tmp_images/camas_mov.jpg"
    - service: notify.iphone_tyf
      data:
        message: Alguien está en las camas del huerto!
        data:
          attachment:
            url: "https://i22g9issoj09w2y8s84fi5swgcjrblsi.ui.nabu.casa/local/tmp_images/camas_mov.jpg"
            content-type: jpeg
            hide_thumbnail: false
    - service: script.sonos_play
      data:
        sonos_entity: media_player.office
        volume: 0.9
        delay: 00:00:05
        media_content_id: http://192.168.100.50:8123/local/sounds/guinea_pig.mp3




alert:
  high_temperature_alert:
    name: Algunas temperaturas son demasiado altas
    done_message: Temperaturas normales
    entity_id: input_boolean.high_temperature
    state: 'on'
    repeat: 1
    can_acknowledge: true
    notifiers:
      - notify.iphone_tyf
  high_gas_lp:
    name: Alarma de gas en cocina
    done_message: Niveles de gas normales
    entity_id: binary_sensor.gas_alto
    state: 'on'
    repeat: 1
    can_acknowledge: true
    notifiers:
      - notify.iphone_tyf


