weather:
  - platform: darksky
    api_key: !secret darksky_api_key

ambient_station:
  api_key: !secret aw_api_key
  app_key: !secret aw_app_key

sensor:
  - platform: darksky
    api_key: !secret darksky_api_key
    hourly_forecast:
      - 0
      - 1
    monitored_conditions:
      - summary
      - icon
      - precip_probability
      - nearest_storm_distance
      - nearest_storm_bearing
    scan_interval: '00:20' 
  # - platform: rest
  #   resource: "http://192.168.100.50:8090/get_weather"
  #   name: "Weather station"
  #   scan_interval: 120
  #   force_update: true
  #   json_attributes:
  #       - humidity
  #       - temperature
  #       - date
  #       - wind_direction
  #       - wind_speed
  #       - rain_mm_day
  # - platform: template
  #   sensors:
  #     temperature_outside:
  #       entity_id: sensor.weather_station
  #       friendly_name: 'Temperatura Exterior'
  #       value_template: '{{ states.sensor.weather_station.attributes.temperature | float }}'
  #       unit_of_measurement: "°C"
  #     wind_speed_outside:
  #       entity_id: sensor.weather_station
  #       value_template: '{{ states.sensor.weather_station.attributes.wind_speed }}'
  #       unit_of_measurement: "km/h"
  #     cumulative_rain_day:
  #       entity_id: sensor.weather_station
  #       value_template:  "{{ state_attr('sensor.weather_station', 'rain_mm_day') | float }}"
  #       unit_of_measurement: "mm"

  - platform: template
    sensors:
      rain_mm_twoday:
        entity_id:
          - sensor.cumulative_rain_yesterday
          - sensor.cumulative_rain_today
        value_template: '{{ ((states.sensor.cumulative_rain_yesterday.state | float) + (states.sensor.cumulative_rain_today.state | float)) | round(1) }}'
        unit_of_measurement: mm

  - platform: sql
    db_url: !secret hass_db
    queries:
      - name: cumulative_rain_yesterday
        query: "select coalesce(25.4*max(state+0),0) as maximum from states where entity_id = 'sensor.cuauhtemoc_daily_rain_2' and date(convert_tz(last_updated,'UTC','US/Central'))  = subdate(date(convert_tz(now(), 'UTC','US/Central')),1);"
        column: 'maximum'
        unit_of_measurement: mm
      - name: cumulative_rain_today
        query: "select coalesce(25.4*max(state+0), 0) as maximum from states where entity_id = 'sensor.cuauhtemoc_daily_rain_2' and date(convert_tz(last_updated,'UTC','US/Central'))  = subdate(date(convert_tz(now(), 'UTC','US/Central')),0);"
        column: 'maximum'
        unit_of_measurement: mm

### bad weather sensor ############
binary_sensor:
  - platform: trend
    sensors:
      pressure_falling:
        entity_id: sensor.cuauhtemoc_abs_pressure_2
        device_class: safety
        max_samples: 1000
        sample_duration: 3600
        min_gradient: -0.000016

homeassistant:
  customize:
    sensor.cuauhtemoc_humidity_2:
      friendly_name: Humedad Exterior
    sensor.cuauhtemoc_temp_2:
      friendly_name: Temperatura Exterior
    binary_sensor.pressure_falling_2:
      friendly_name: Mal clima

# Rain notification
automation:
  trigger:
    platform: numeric_state
    entity_id: sensor.dark_sky_precip_probability_1h
    above: 75
  action:
    service: notify.iphone_tyf
    data:
      message: "Es probable que llueva en la próxima hora!"

